### ISSUE TITLE
【WordPress 6.6.2】Notice: 函数 wp_deregister_script 的调用方法不正确

### ISSUE THREAD

**Issue by sickworm** [imjeff/wordpress-textonly#1]
安装 textonly 后，主页会报错：

`Notice: 函数 wp_deregister_script 的调用方法不正确。 脚本和样式应在 wp_enqueue_scripts 、 admin_enqueue_scripts 和 login_enqueue_scripts 钩子函数之后再加入加载队列（enqueue）或注册（register）。 此通知由 l10n 触发。 请查阅[调试 WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/)来获取更多信息。 （这个消息是在 3.3.0 版本添加的。） in /var/www/blog/wp-includes/functions.php on line 6085`

我发现可以通过注释这个文件来修复这个问题：
`/var/www/blog/wp-content/themes/wordpress-textonly-1.0.2`

// 禁用l10n.js
// wp_deregister_script('l10n');

paper 主题也有这个问题

主题很好，感谢你的付出！

**Comment by imjeff** [comment]
在我目前两个环境中未能复现问题。可以直接注释或通过以下方式禁用：

```
if ( !is_admin() ) {
function my_init_method() {
wp_deregister_script( 'l10n' );
}
add_action('init', 'my_init_method'); 
}
```
